#from openmdao.api import Component
from numpy import zeros
def FstModel(self, i, firstname):
	#def __init__(self):%i:
                super(FstModel,self).__init__()

		# Description
		self.add_param('%s:description%i'(firstname, i), val='')

                ###################
		# Fst file vartrees
                ###################

		#self.fst_sim_ctrl = FstSimCtrl()
		self.add_param('%s:fst_sim_ctrl:%i:Echo'%(firstname, i), val=False)
		self.add_param('%s:fst_sim_ctrl:%i:AbortLevel'%(firstname, i), val='')
		self.add_param('%s:fst_sim_ctrl:%i:TMax'%(firstname, i), val=0.)
		self.add_param('%s:fst_sim_ctrl:%i:DT'%(firstname, i), val=0.)
		self.add_param('%s:fst_sim_ctrl:%i:InterpOrder'%(firstname, i), val=0)
		self.add_param('%s:fst_sim_ctrl:%i:NumCrctn'%(firstname, i), val=0)
		self.add_param('%s:fst_sim_ctrl:%i:DT_UJac'%(firstname, i), val=0.)
		self.add_param('%s:fst_sim_ctrl:%i:UJacSclFact'%(firstname, i), val=0.)
		self.add_param('%s:fst_sim_ctrl:%i:ADAMSPrep'%(firstname, i), val=0)
		self.add_param('%s:fst_sim_ctrl:%i:AnalMode'%(firstname, i), val=0)

		#self.ftr_swtchs_flgs = FtrSwtchsFlgs()
		self.add_param('%s:ftr_swtchs_flgs:%i:CompElast'%(firstname, i), val=0)
		self.add_param('%s:ftr_swtchs_flgs:%i:CompInflow'%(firstname, i), val=0)
		self.add_param('%s:ftr_swtchs_flgs:%i:CompAero'%(firstname, i), val=0)
		self.add_param('%s:ftr_swtchs_flgs:%i:CompServo'%(firstname, i), val=0)
		self.add_param('%s:ftr_swtchs_flgs:%i:CompHydro'%(firstname, i), val=0)
		self.add_param('%s:ftr_swtchs_flgs:%i:CompSub'%(firstname, i), val=0)
		self.add_param('%s:ftr_swtchs_flgs:%i:CompMooring'%(firstname, i), val=0)
		self.add_param('%s:ftr_swtchs_flgs:%i:CompIce'%(firstname, i), val=0)
		self.add_param('%s:ftr_swtchs_flgs:%i:CompNoise'%(firstname, i), val=0)

		#self.input_files = InputFiles()
		self.add_param('%s:input_files:%i:EDFile'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:BDBldFile1'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:BDBldFile2'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:BDBldFile3'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:InflowFile'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:AeroFile'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:ServoFile'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:HydroFile'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:SubFile'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:MooringFile'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:IceFile'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:ADFile'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:NoiseFile'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:ADAMSFile'%(firstname, i), val='')
		self.add_param('%s:input_files:%i:LinFile'%(firstname, i), val='')
               
		#self.fst_output_params = FstOutputParams()
		self.add_param('%s:fst_output_params:%i:SumPrint'%(firstname, i), val=False)
		self.add_param('%s:fst_output_params:%i:SttsTime'%(firstname, i), val=0.)
		self.add_param('%s:fst_output_params:%i:ChkptTime'%(firstname, i), val=0.)
		self.add_param('%s:fst_output_params:%i:DT_Out'%(firstname, i), val=0.)
		self.add_param('%s:fst_output_params:%i:OutFileFmt'%(firstname, i), val=0)
		self.add_param('%s:fst_output_params:%i:TabDelim'%(firstname, i), val=False)
		self.add_param('%s:fst_output_params:%i:OutFmt'%(firstname, i), val='')

		#self.visualization = Visualization()
		self.add_param('%s:visualization:%i:WrVTK'%(firstname, i), val=0)
		self.add_param('%s:visualization:%i:VTK_type'%(firstname, i), val=0)
		self.add_param('%s:visualization:%i:VTK_fields'%(firstname, i), val=0)
		self.add_param('%s:visualization:%i:VTK_fps'%(firstname, i), val=0)

                #self.linearization = Linearization()
                self.add_param('%s:linearization:%i:Linearize'%(firstname, i), val=False)
                self.add_param('%s:linearization:%i:NLinTimes'%(firstname, i), val=2)
                self.add_param('%s:linearization:%i:LinTimes'%(firstname, i), val=(30, 60))
                self.add_param('%s:linearization:%i:LinInputs'%(firstname, i), val=1)
                self.add_param('%s:linearization:%i:LinOutputs'%(firstname, i), val=1)
                self.add_param('%s:linearization:%i:LinOutJac'%(firstname, i), val=False)
                self.add_param('%s:linearization:%i:LinOutMod'%(firstname, i), val=False)

                ###################
		# Elastodyn vartrees
                ###################
		#self.ed_sim_ctrl = EdSimCtrl()
		self.add_param('%s:ed_sim_ctrl:%i:Echo'%(firstname, i), val=False)
		self.add_param('%s:ed_sim_ctrl:%i:Method'%(firstname, i), val=0)
		self.add_param('%s:ed_sim_ctrl:%i:DT'%(firstname, i), val=0.)

		#self.envir_cond = EnvirCond()
		self.add_param('%s:envir_cond:%i:Gravity'%(firstname, i), val=0.)

		#self.dof = DOF()
		self.add_param('%s:dof:%i:FlapDOF1'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:FlapDOF2'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:EdgeDOF'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:TeetDOF'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:DrTrDOF'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:GenDOF'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:YawDOF'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:TwFADOF1'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:TwFADOF2'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:TwSSDOF1'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:TwSSDOF2'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:PtfmSgDOF'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:PtfmSwDOF'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:PtfmHvDOF'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:PtfmRDOF'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:PtfmPDOF'%(firstname, i), val=False)
		self.add_param('%s:dof:%i:PtfmYDOF'%(firstname, i), val=False)

		#self.init_conds = InitConds()
		self.add_param('%s:init_conds:%i:OoPDefl'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:IPDefl'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:BlPitch1'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:BlPitch2'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:BlPitch3'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:TeetDefl'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:Azimuth'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:RotSpeed'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:NacYaw'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:TTDspFA'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:TTDspSS'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:PtfmSurge'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:PtfmHeave'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:PtfmRoll'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:PtfmPitch'%(firstname, i), val=0.0)
		self.add_param('%s:init_conds:%i:PtfmYaw'%(firstname, i), val=0.0)

		#self.turb_config = TurbConfig()
		self.add_param('%s:turb_config:%i:NumBl'%(firstname, i), val=0)
		self.add_param('%s:turb_config:%i:TipRad'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:HubRad'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:PreCone1'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:PreCone2'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:PreCone3'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:HubCM'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:UndSling'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:Delta3'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:AzimB1Up'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:OverHang'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:ShftGagL'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:ShftTilt'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:NacCMxn'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:NacCMyn'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:NacCMzn'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:NcIMUxn'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:NcIMUyn'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:NcIMUzn'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:Twr2Shft'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:TowerHt'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:TowerBsHt'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:PtfmCMxt'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:PtfmCMyt'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:PtfmCMzt'%(firstname, i), val=0.)
		self.add_param('%s:turb_config:%i:PtfmRefzt'%(firstname, i), val=0.)

		#self.mass_inertia = MassInertia()
		self.add_param('%s:mass_inertia:%i:TipMass1'%(firstname, i), val=0.)
		self.add_param('%s:mass_inertia:%i:TipMass2'%(firstname, i), val=0.)
		self.add_param('%s:mass_inertia:%i:HubMass'%(firstname, i), val=0.)
		self.add_param('%s:mass_inertia:%i:HubIner'%(firstname, i), val=0.)
		self.add_param('%s:mass_inertia:%i:GenIner'%(firstname, i), val=0.)
		self.add_param('%s:mass_inertia:%i:NacMass'%(firstname, i), val=0.)
		self.add_param('%s:mass_inertia:%i:NacYIner'%(firstname, i), val=0.)
		self.add_param('%s:mass_inertia:%i:YawBrMass'%(firstname, i), val=0.)
		self.add_param('%s:mass_inertia:%i:PtfmMass'%(firstname, i), val=0.)
		self.add_param('%s:mass_inertia:%i:PtfmRIner'%(firstname, i), val=0.)
		self.add_param('%s:mass_inertia:%i:PtfmPIner'%(firstname, i), val=0.)
		self.add_param('%s:mass_inertia:%i:PtfmYIner'%(firstname, i), val=0.)

		#self.blade_struc = BladeStruc()
		self.add_param('%s:blade_struc:%i:BldNodes'%(firstname, i), val=0)
		self.add_param('%s:blade_struc:%i:BldFile1'%(firstname, i), val='')
		self.add_param('%s:blade_struc:%i:BldFile2'%(firstname, i), val='')
		self.add_param('%s:blade_struc:%i:BldFile3'%(firstname, i), val='')
		self.add_param('%s:blade_struc:%i:NBlInpSt'%(firstname, i), val=0)
		self.add_param('%s:blade_struc:%i:CalcBMode'%(firstname, i), val=False)
		self.add_param('%s:blade_struc:%i:BldFlDmp1'%(firstname, i), val=0.)
		self.add_param('%s:blade_struc:%i:BldFlDmp2'%(firstname, i), val=0.)
		self.add_param('%s:blade_struc:%i:BldEdDmp1'%(firstname, i), val=0.)
		self.add_param('%s:blade_struc:%i:FlStTunr1'%(firstname, i), val=0.)
		self.add_param('%s:blade_struc:%i:FlStTunr2'%(firstname, i), val=0.)
		self.add_param('%s:blade_struc:%i:AdjBlMs'%(firstname, i), val=0.)
		self.add_param('%s:blade_struc:%i:AdjFlSt'%(firstname, i), val=0.)
		self.add_param('%s:blade_struc:%i:AdjEdSt'%(firstname, i), val=0.)
		self.add_param('%s:blade_struc:%i:BlFract', zeros([1]))
		self.add_param('%s:blade_struc:%i:AeroCent', zeros([1]))
		self.add_param('%s:blade_struc:%i:PitchAxis', zeros([1]))
		self.add_param('%s:blade_struc:%i:StrcTwst', zeros([1]))
		self.add_param('%s:blade_struc:%i:BMassDen', zeros([1]))
		self.add_param('%s:blade_struc:%i:FlpStff', zeros([1]))
		self.add_param('%s:blade_struc:%i:EdgStff', zeros([1]))
		self.add_param('%s:blade_struc:%i:GJStff', zeros([1]))
		self.add_param('%s:blade_struc:%i:EAStff', zeros([1]))
		self.add_param('%s:blade_struc:%i:Alpha', zeros([1]))
		self.add_param('%s:blade_struc:%i:FlpIner', zeros([1]))
		self.add_param('%s:blade_struc:%i:EdgIner', zeros([1]))
		self.add_param('%s:blade_struc:%i:PrecrvRef', zeros([1]))
		self.add_param('%s:blade_struc:%i:PreswpRef', zeros([1]))
		self.add_param('%s:blade_struc:%i:FlpcgOf', zeros([1]))
		self.add_param('%s:blade_struc:%i:Edgcgof', zeros([1]))
		self.add_param('%s:blade_struc:%i:FlpEAOf', zeros([1]))
		self.add_param('%s:blade_struc:%i:EdgEAOf', zeros([1]))
		self.add_param('%s:blade_struc:%i:BldFl1Sh', zeros([1]))
		self.add_param('%s:blade_struc:%i:BldFl2Sh', zeros([1]))
		self.add_param('%s:blade_struc:%i:BldEdgSh', zeros([1]))

		#self.rotor_teeter = RotorT:%i:eter()
		self.add_param('%s:rotor_teeter:%i:TeetMod'%(firstname, i), val=0)
		self.add_param('%s:rotor_teeter:%i:TeetDmpP'%(firstname, i), val=0.0)
		self.add_param('%s:rotor_teeter:%i:TeetDmp'%(firstname, i), val=0.0)
		self.add_param('%s:rotor_teeter:%i:TeetCDmp'%(firstname, i), val=0.0)
		self.add_param('%s:rotor_teeter:%i:TeetSStP'%(firstname, i), val=0.0)
		self.add_param('%s:rotor_teeter:%i:TeetHStP'%(firstname, i), val=0.0)
		self.add_param('%s:rotor_teeter:%i:TeetSSSp'%(firstname, i), val=0.0)
		self.add_param('%s:rotor_teeter:%i:TeetHSSp'%(firstname, i), val=0.0)

		#self.drivetrain = DriveTrai:%i:()
		self.add_param('%s:drivetrain:%i:GBoxEff'%(firstname, i), val=0.0)
		self.add_param('%s:drivetrain:%i:GBRatio'%(firstname, i), val=0.0)
		self.add_param('%s:drivetrain:%i:DTTorSpr'%(firstname, i), val=0.0)
		self.add_param('%s:drivetrain:%i:DTTorDmp'%(firstname, i), val=0.0)
		self.add_param('%s:drivetrain:%i:GBRevers'%(firstname, i), val=0.0)
		self.add_param('%s:drivetrain:%i:DynBrkFi'%(firstname, i), val=0.0)

		#self.furling = Furling()
		self.add_param('%s:furling:%i:Furling'%(firstname, i), val=False)
		self.add_param('%s:furling:%i:FurlFile'%(firstname, i), val='')

		#self.platform = Platform()
		self.add_param('%s:platform:%i:PtfmModel'%(firstname, i), val=0)
		self.add_param('%s:platform:%i:PtfmFile'%(firstname, i), val='')

		#self.tower = Tower()
		self.add_param('%s:tower:%i:TwrNodes'%(firstname, i), val=0)
		self.add_param('%s:tower:%i:TwrFile'%(firstname, i), val='')
		self.add_param('%s:tower:%i:NTwInptSt'%(firstname, i), val=0)
		self.add_param('%s:tower:%i:CalcTMode'%(firstname, i), val=False)
		self.add_param('%s:tower:%i:TwrFADmp1'%(firstname, i), val=0.)
		self.add_param('%s:tower:%i:TwrFADmp2'%(firstname, i), val=0.)
		self.add_param('%s:towSr:%i:TwrSSDmp1'%(firstname, i), val=0.)
		self.add_param('%s:towSr:%i:TwrSSDmp2'%(firstname, i), val=0.)
		self.add_param('%s:towSr:%i:FAStTunr1'%(firstname, i), val=0.)
		self.add_param('%s:towSr:%i:FAStTunr2'%(firstname, i), val=0.)
		self.add_param('%s:towSr:%i:SSStTunr1'%(firstname, i), val=0.)
		self.add_param('%s:towSr:%i:SSStTunr2'%(firstname, i), val=0.)
		self.add_param('%s:towSr:%i:AdjTwMa'%(firstname, i), val=0.)
		self.add_param('%s:towSr:%i:AdjFASt'%(firstname, i), val=0.)
		self.add_param('%s:towSr:%i:AdjSSSt'%(firstname, i), val=0.)
		self.add_param('%s:towSr:%i:HtFract'%(firstname, i), val=zeros([1]))
		self.add_param('%s:towSr:%i:TMassDen'%(firstname, i), val=zeros([1]))
		self.add_param('%s:towSr:%i:TwFAStif'%(firstname, i), val=zeros([1]))
		self.add_param('%s:towSr:%i:TwSSStif'%(firstname, i), val=zeros([1]))
		self.add_param('%s:towSr:%i:TwGJStif'%(firstname, i), val=zeros([1]))
		self.add_param('%s:towSr:%i:TwEAStif'%(firstname, i), val=zeros([1]))
		self.add_param('%s:towSr:%i:TwFAIner'%(firstname, i), val=zeros([1]))
		self.add_param('%s:towSr:%i:TwSSIner'%(firstname, i), val=zeros([1]))
		self.add_param('%s:towSr:%i:TwFAcgOf'%(firstname, i), val=zeros([1]))
		self.add_param('%s:towSr:%i:TwSScgOf'%(firstname, i), val=zeros([1]))
		self.add_param('%s:towSr:%i:TwFAM1Sh'%(firstname, i), val=zeros([1]))
		self.add_param('%s:towSr:%i:TwFAM2Sh'%(firstname, i), val=zeros([1]))
		self.add_param('%s:towSr:%i:TwSSM1Sh'%(firstname, i), val=zeros([1]))
		self.add_param('%s:towSr:%i:TwSSM2Sh'%(firstname, i), val=zeros([1]))

		#self.ed_out_params = EdOutParams()
		self.add_param('%s:ed_out_params:%i:SumPrint'%(firstname, i), val=False)
		self.add_param('%s:ed_out_params:%i:OutFile'%(firstname, i), val=0)
		self.add_param('%s:ed_out_params:%i:TabDelim'%(firstname, i), val=False)
		self.add_param('%s:ed_out_params:%i:OutFmt'%(firstname, i), val='')
		self.add_param('%s:ed_out_params:%i:TStart'%(firstname, i), val=0.0)
		self.add_param('%s:ed_out_params:%i:DecFact'%(firstname, i), val=0.0)
		self.add_param('%s:ed_out_params:%i:NTwGages'%(firstname, i), val=0)
		self.add_param('%s:ed_out_params:%i:TwrGagNd'%(firstname, i), val=[])
		self.add_param('%s:ed_out_params:%i:NBlGages'%(firstname, i), val=0)
		self.add_param('%s:ed_out_params:%i:BldGagNd'%(firstname, i), val=[])

                ##################:%i:
		# Wind vartrees
                ###################
		#self.inflow_wind = InflowWind()
		self.add_param('%s:inflow_wind:%i:Echo'%(firstname, i), val=False)
		self.add_param('%s:inflow_wind:%i:WindType'%(firstname, i), val=0)
		self.add_param('%s:inflow_wind:%i:PropagationDir'%(firstname, i), val=0.)
		self.add_param('%s:inflow_wind:%i:NWindVel'%(firstname, i), val=0)
		self.add_param('%s:inflow_wind:%i:WindVxiList'%(firstname, i), val=0.)
		self.add_param('%s:inflow_wind:%i:WindVyiList'%(firstname, i), val=0.)
		self.add_param('%s:inflow_wind:%i:WindVziList'%(firstname, i), val=0.)

		#self.steady_wind_params = SteadyWindParams()
		self.add_param('%s:steady_wind_params:%i:HWindSpeed'%(firstname, i), val=0.)
		self.add_param('%s:steady_wind_params:%i:RefHt'%(firstname, i), val=0.)
		self.add_param('%s:steady_wind_params:%i:PLexp'%(firstname, i), val=0.)

		#self.uniform_wind_params = UniformWindParams()
		self.add_param('%s:uniform_wind_params:%i:Filename'%(firstname, i), val='')
		self.add_param('%s:uniform_wind_params:%i:RefHt'%(firstname, i), val=0.)
		self.add_param('%s:uniform_wind_params:%i:RefLength'%(firstname, i), val=0.)

		#self.turbsim_wind_params = TurbSimWindParams()
		self.add_param('%s:turbsim_wind_params:%i:Filename'%(firstname, i), val='')

		#self.bladed_wind_params = BladedWindParams()
		self.add_param('%s:bladed_wind_params:%i:FilenameRoot'%(firstname, i), val='')
		self.add_param('%s:bladed_wind_params:%i:TowerFile'%(firstname, i), val=False)

		#self.hawc_wind_params = HAWCWindParams()
		self.add_param('%s:hawc_wind_params:%i:FileName_u'%(firstname, i), val='')
		self.add_param('%s:hawc_wind_params:%i:FileName_v'%(firstname, i), val='')
		self.add_param('%s:hawc_wind_params:%i:FileName_w'%(firstname, i), val='')
		self.add_param('%s:hawc_wind_params:%i:nx'%(firstname, i), val=0)
		self.add_param('%s:hawc_wind_params:%i:ny'%(firstname, i), val=0)
		self.add_param('%s:hawc_wind_params:%i:nz'%(firstname, i), val=0)
		self.add_param('%s:hawc_wind_params:%i:dx'%(firstname, i), val=0.)
		self.add_param('%s:hawc_wind_params:%i:dy'%(firstname, i), val=0.)
		self.add_param('%s:hawc_wind_params:%i:dz'%(firstname, i), val=0.)
		self.add_param('%s:hawc_wind_params:%i:RefHt'%(firstname, i), val=0.)
		self.add_param('%s:hawc_wind_params:%i:ScaleMethod'%(firstname, i), val=0)
		self.add_param('%s:hawc_wind_params:%i:SFx'%(firstname, i), val=0.)
		self.add_param('%s:hawc_wind_params:%i:SFy'%(firstname, i), val=0.)
		self.add_param('%s:hawc_wind_params:%i:SFz'%(firstname, i), val=0.)
		self.add_param('%s:hawc_wind_params:%i:SigmaFx'%(firstname, i), val=0.)
		self.add_param('%s:hawc_wind_params:%i:SigmaFy'%(firstname, i), val=0.)
		self.add_param('%s:hawc_wind_params:%i:SigmaFz'%(firstname, i), val=0.)
		self.add_param('%s:hawc_wind_params:%i:URef'%(firstname, i), val=0.)
		self.add_param('%s:hawc_wind_params:%i:WindProfile'%(firstname, i), val=0)
		self.add_param('%s:hawc_wind_params:%i:PLExp'%(firstname, i), val=0.)
		self.add_param('%s:hawc_wind_params:%i:Z0'%(firstname, i), val=0.)


		#self.inflow_out_params = Inflow:%i:utParams()
		self.add_param('%s:inflow_out_params:%i:SumPrint'%(firstname, i), val=False)

		#self.wnd_wind = WndWind()
		self.add_param('%s:wnd_wind:%i:TimeSteps'%(firstname, i), val=0)
		self.add_param('%s:wnd_wind:%i:Time'%(firstname, i), val=zeros([1]))
		self.add_param('%s:wnd_wind:%i:HorSpd'%(firstname, i), val=zeros([1]))
		self.add_param('%s:wnd_wind:%i:WindDir'%(firstname, i), val=zeros([1]))
		self.add_param('%s:wnd_wind:%i:VerSpd'%(firstname, i), val=zeros([1]))
		self.add_param('%s:wnd_wind:%i:HorShr'%(firstname, i), val=zeros([1]))
		self.add_param('%s:wnd_wind:%i:VerShr'%(firstname, i), val=zeros([1]))
		self.add_param('%s:wnd_wind:%i:LnVShr'%(firstname, i), val=zeros([1]))
		self.add_param('%s:wnd_wind:%i:GstSpd'%(firstname, i), val=zeros([1]))

                ###################
		# AeroDyn vartrees
                ###################
		#self.aerodyn = AeroDyn()
		self.add_param('%s:aerodyn:%i:SysUnits'%(firstname, i), val='SI')
		self.add_param('%s:aerodyn:%i:StallMod'%(firstname, i), val='BEDOES')
		self.add_param('%s:aerodyn:%i:UseCM'%(firstname, i), val='NO_CM')
		self.add_param('%s:aerodyn:%i:InfModel'%(firstname, i), val='EQUIL')
		self.add_param('%s:aerodyn:%i:IndModel'%(firstname, i), val='SWIRL')
		self.add_param('%s:aerodyn:%i:AToler'%(firstname, i), val=0.)
		self.add_param('%s:aerodyn:%i:TLModel'%(firstname, i), val='PRANDtl')
		self.add_param('%s:aerodyn:%i:HLModel'%(firstname, i), val='PRANDTl')
		self.add_param('%s:aerodyn:%i:WindFile'%(firstname, i), val='')
		self.add_param('%s:aerodyn:%i:wind_file_type'%(firstname, i), val='hh')
		self.add_param('%s:aerodyn:%i:HH'%(firstname, i), val=0.)
		self.add_param('%s:aerodyn:%i:TwrShad'%(firstname, i), val=0.)
		self.add_param('%s:aerodyn:%i:ShadHWid'%(firstname, i), val=9999.9)
		self.add_param('%s:aerodyn:%i:T_Shad_Refpt'%(firstname, i), val=9999.9)
		self.add_param('%s:aerodyn:%i:AirDens'%(firstname, i), val=1.225)
		self.add_param('%s:aerodyn:%i:KinVisc'%(firstname, i), val=1.464e-5)
		self.add_param('%s:aerodyn:%i:DTAero'%(firstname, i), val=0.02479)

		#self.blade_aero = AeroDynBlade()
		self.add_param('%s:blade_aero:%i:NumFoil'%(firstname, i), val=0)
		self.add_param('%s:blade_aero:%i:FoilNm'%(firstname, i), val=zeros([1]))
		self.add_param('%s:blade_aero:%i:af_data'%(firstname, i), val=[])
		self.add_param('%s:blade_aero:%i:BldNodes'%(firstname, i), val=zeros([1]))
		self.add_param('%s:blade_aero:%i:AeroTwst'%(firstname, i), val=zeros([1]))
		self.add_param('%s:blade_aero:%i:DRNodes'%(firstname, i), val=zeros([1]))
		self.add_param('%s:blade_aero:%i:Chord'%(firstname, i), val=zeros([1]))
		self.add_param('%s:blade_aero:%i:NFoil'%(firstname, i), val=zeros([1]))
		self.add_param('%s:blade_aero:%i:PrnElm'%(firstname, i), val=zeros([1]))

                ###################
		# ServoDyn vartrees
                ###################
		#self.sd_sim_ctrl = SdSimCtrl()
		self.add_param('%s:sd_sim_ctrl:%i:Echo'%(firstname, i), val=False)
		self.add_param('%s:sd_sim_ctrl:%i:DT'%(firstname, i), val=0.)
                
		#self.pitch_ctrl = PitchCtrl()
		self.add_param('%s:pitch_ctrl:%i:PCMode'%(firstname, i), val=0)
		self.add_param('%s:pitch_ctrl:%i:TPCOn'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:TPitManS1'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:TPitManS2'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:TPitManS3'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:TPitManE1'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:TPitManE2'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:TPitManE3'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:PitManRat1'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:PitManRat2'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:PitManRat3'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:BlPitchF1'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:BlPitchF2'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:BlPitchF3'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:BlPitch1'%(firstname, i), val=0.)
		self.add_param('%s:pitch_ctrl:%i:BlPitch2'%(firstname, i), val=0.)

		#self.gen_torq_ctrl = GenTorqCtrl()
		self.add_param('%s:gen_torq_ctrl:%i:VSContrl'%(firstname, i), val=0)
		self.add_param('%s:gen_torq_ctrl:%i:GenModel'%(firstname, i), val=0)
		self.add_param('%s:gen_torq_ctrl:%i:GenEff'%(firstname, i), val=0.)
		self.add_param('%s:gen_torq_ctrl:%i:GenTiStr'%(firstname, i), val=False)
		self.add_param('%s:gen_torq_ctrl:%i:GenTiStp'%(firstname, i), val=False)
		self.add_param('%s:gen_torq_ctrl:%i:SpdGenOn'%(firstname, i), val=0.)
		self.add_param('%s:gen_torq_ctrl:%i:TimGenOn'%(firstname, i), val=0.)
		self.add_param('%s:gen_torq_ctrl:%i:TimGenOf'%(firstname, i), val=0.)

		#self.var_speed_torq_ctrl = VarSpeedTorqCtrl()
                self.add_param('%s:var_speed_torq_ctrl:%i:VS_RtGnSp'%(firstname, i), val=0.)
                self.add_param('%s:var_speed_torq_ctrl:%i:VS_RtTq'%(firstname, i), val=0.)
                self.add_param('%s:var_speed_torq_ctrl:%i:VS_Rgn2K'%(firstname, i), val=0.)
                self.add_param('%s:var_speed_torq_ctrl:%i:VS_SlPc'%(firstname, i), val=0.)

		#self.induct_gen = InductGen()
		self.add_param('%s:induct_gen:%i:SIG_SlPc'%(firstname, i), val=0.)
		self.add_param('%s:induct_gen:%i:SIG_SySp'%(firstname, i), val=0.)
		self.add_param('%s:induct_gen:%i:SIG_RtTq'%(firstname, i), val=0.)
		self.add_param('%s:induct_gen:%i:SIG_PORt'%(firstname, i), val=0.)

		#self.theveq_induct_gen = ThevEqInductGen()
		self.add_param('%s:theveq_induct_gen:%i:TEC_Freq'%(firstname, i), val=0.)
		self.add_param('%s:theveq_induct_gen:%i:TEC_NPol'%(firstname, i), val=0)
		self.add_param('%s:theveq_induct_gen:%i:TEC_SRes'%(firstname, i), val=0.)
		self.add_param('%s:theveq_induct_gen:%i:TEC_RRes'%(firstname, i), val=0.)
		self.add_param('%s:theveq_induct_gen:%i:TEC_VLL'%(firstname, i), val=0.)
		self.add_param('%s:theveq_induct_gen:%i:TEC_SLR'%(firstname, i), val=0.)
		self.add_param('%s:theveq_induct_gen:%i:TEC_RLR'%(firstname, i), val=0.)
		self.add_param('%s:theveq_induct_gen:%i:TEC_MR'%(firstname, i), val=0.)

		#self.shaft_brake = ShaftBrake()
		self.add_param('%s:shaft_brake:%i:HSSBrMode'%(firstname, i), val=0)
		self.add_param('%s:shaft_brake:%i:THSSBrDp'%(firstname, i), val=0.)
		self.add_param('%s:shaft_brake:%i:HSSBrDT'%(firstname, i), val=0.)
		self.add_param('%s:shaft_brake:%i:HSSBrTqF'%(firstname, i), val=0.)

		#self.nac_yaw_ctrl = NacYawCtrl()
		self.add_param('%s:nac_yaw_ctrl:%i:YCMode'%(firstname, i), val=0)
		self.add_param('%s:nac_yaw_ctrl:%i:TYCOn'%(firstname, i), val=0.)
		self.add_param('%s:nac_yaw_ctrl:%i:YawNeut'%(firstname, i), val=0.)
		self.add_param('%s:nac_yaw_ctrl:%i:YawSpr'%(firstname, i), val=0.)
		self.add_param('%s:nac_yaw_ctrl:%i:YawDamp'%(firstname, i), val=0.)
		self.add_param('%s:nac_yaw_ctrl:%i:TYawManS'%(firstname, i), val=0.)
		self.add_param('%s:nac_yaw_ctrl:%i:YawManRat'%(firstname, i), val=0.)
		self.add_param('%s:nac_yaw_ctrl:%i:NacYawF'%(firstname, i), val=0.)

		#self.tip_brake = TipBrake()
		self.add_param('%s:tip_brake:%i:TiDynBrk'%(firstname, i), val=0.)
		self.add_param('%s:tip_brake:%i:TTpBrDp1'%(firstname, i), val=0.)
		self.add_param('%s:tip_brake:%i:TTpBrDp2'%(firstname, i), val=0.)
		self.add_param('%s:tip_brake:%i:TTpBrDp3'%(firstname, i), val=0.)
		self.add_param('%s:tip_brake:%i:TBDepISp1'%(firstname, i), val=0.)
		self.add_param('%s:tip_brake:%i:TBDepISp2'%(firstname, i), val=0.)
		self.add_param('%s:tip_brake:%i:TBDepISp3'%(firstname, i), val=0.)
		self.add_param('%s:tip_brake:%i:TBDrConN'%(firstname, i), val=0.)
		self.add_param('%s:tip_brake:%i:TBDrConD'%(firstname, i), val=0.)
		self.add_param('%s:tip_brake:%i:TpBrDT'%(firstname, i), val=0.)

		#self.tuned_mass_damper = TunedMassDamp()
		self.add_param('%s:tuned_mass_damper:%i:CompNTMD'%(firstname, i), val=0.)
		self.add_param('%s:tuned_mass_damper:%i:NTMDfile'%(firstname, i), val='')
		self.add_param('%s:tuned_mass_damper:%i:CompTTMD'%(firstname, i), val=0.)
		self.add_param('%s:tuned_mass_damper:%i:TTMDfile'%(firstname, i), val='')

		#self.bladed_interface = BladedInterface()
		self.add_param('%s:bladed_interface:%i:DLL_FileName'%(firstname, i), val='')
		self.add_param('%s:bladed_interface:%i:DLL_InFile'%(firstname, i), val='')
		self.add_param('%s:bladed_interface:%i:DLL_ProcName'%(firstname, i), val='')
		self.add_param('%s:bladed_interface:%i:DLL_DT'%(firstname, i), val='')
		self.add_param('%s:bladed_interface:%i:DLL_Ramp'%(firstname, i), val=False)
		self.add_param('%s:bladed_interface:%i:BPCutoff'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:NacYaw_North'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:Ptch_Cntrl'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:Ptch_SetPnt'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:Ptch_Min'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:Ptch_Max'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:PtchRate_Min'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:PtchRate_Max'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:Gain_OM'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:GenSpd_MinOM'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:GenSpd_MaxOM'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:GenSpd_Dem'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:GenPwr_Dem'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:DLL_NumTrq'%(firstname, i), val=0.)
		self.add_param('%s:bladed_interface:%i:GenSpd_TLU'%(firstname, i), val=zeros([0]))
		self.add_param('%s:bladed_interface:%i:GenTrq_TLU'%(firstname, i), val=zeros([0]))

		#self.sd_out_params = SdOutParams()
		self.add_param('%s:sd_out_params:%i:SumPrint'%(firstname, i), val=False)
		self.add_param('%s:sd_out_params:%i:OutFile'%(firstname, i), val=0)
		self.add_param('%s:sd_out_params:%i:TabDelim'%(firstname, i), val=False)
		self.add_param('%s:sd_out_params:%i:OutFmt'%(firstname, i), val='')
		self.add_param('%s:sd_out_params:%i:TStart'%(firstname, i), val=0.)
		
		# List of Outputs (all input files -- FST, ED, SD)
		# TODO:%i: Update FstOutput for a few new outputs in FAST8
		#self.outlist = FstOutput()   # 
		self.add_param('%s:outlist:%i:description'%(firstname, i), val='')











