#from openmdao.api import Component
from numpy import zeros
def FstModel(self, firstname):
	#def __init__(self):
                #super(FstModel, self).__init__()

		# Description
		self.add_param('%s:description'%(firstname), val='')

                # I/O
		self.add_param('%s:fst_directory'%(firstname), val='FST8inputfiles') # Template directory
		self.add_param('%s:FSTInputFile'%(firstname), val='Test01.fst')  #Master FAST file
		self.add_param('%s:FSTexe'%(firstname), val='openfast')  #Master FAST file
             

                ###################
		# Fst file vartrees
                ###################

		#self.fst_sim_ctrl = FstSimCtrl()
		self.add_param('%s:fst_sim_ctrl:Echo'%(firstname), val=False)
		self.add_param('%s:fst_sim_ctrl:AbortLevel'%(firstname), val='')
		self.add_param('%s:fst_sim_ctrl:TMax'%(firstname), val=0.)
		self.add_param('%s:fst_sim_ctrl:DT'%(firstname), val=0.)
		self.add_param('%s:fst_sim_ctrl:InterpOrder'%(firstname), val=0)
		self.add_param('%s:fst_sim_ctrl:NumCrctn'%(firstname), val=0)
		self.add_param('%s:fst_sim_ctrl:DT_UJac'%(firstname), val=0.)
		self.add_param('%s:fst_sim_ctrl:UJacSclFact'%(firstname), val=0.)
		self.add_param('%s:fst_sim_ctrl:ADAMSPrep'%(firstname), val=0)
		self.add_param('%s:fst_sim_ctrl:AnalMode'%(firstname), val=0)

		#self.ftr_swtchs_flgs = FtrSwtchsFlgs()
		self.add_param('%s:ftr_swtchs_flgs:CompElast'%(firstname), val=0)
		self.add_param('%s:ftr_swtchs_flgs:CompInflow'%(firstname), val=0)
		self.add_param('%s:ftr_swtchs_flgs:CompAero'%(firstname), val=0)
		self.add_param('%s:ftr_swtchs_flgs:CompServo'%(firstname), val=0)
		self.add_param('%s:ftr_swtchs_flgs:CompHydro'%(firstname), val=0)
		self.add_param('%s:ftr_swtchs_flgs:CompSub'%(firstname), val=0)
		self.add_param('%s:ftr_swtchs_flgs:CompMooring'%(firstname), val=0)
		self.add_param('%s:ftr_swtchs_flgs:CompIce'%(firstname), val=0)
		self.add_param('%s:ftr_swtchs_flgs:CompNoise'%(firstname), val=0)

		#self.input_files = InputFiles()
		self.add_param('%s:input_files:EDFile'%(firstname), val='')
		self.add_param('%s:input_files:BDBldFile1'%(firstname), val='')
		self.add_param('%s:input_files:BDBldFile2'%(firstname), val='')
		self.add_param('%s:input_files:BDBldFile3'%(firstname), val='')
		self.add_param('%s:input_files:InflowFile'%(firstname), val='')
		self.add_param('%s:input_files:AeroFile'%(firstname), val='')
		self.add_param('%s:input_files:ServoFile'%(firstname), val='')
		self.add_param('%s:input_files:HydroFile'%(firstname), val='')
		self.add_param('%s:input_files:SubFile'%(firstname), val='')
		self.add_param('%s:input_files:MooringFile'%(firstname), val='')
		self.add_param('%s:input_files:IceFile'%(firstname), val='')
		self.add_param('%s:input_files:ADFile'%(firstname), val='')
		self.add_param('%s:input_files:NoiseFile'%(firstname), val='')
		self.add_param('%s:input_files:ADAMSFile'%(firstname), val='')
		self.add_param('%s:input_files:LinFile'%(firstname), val='')
               
		#self.fst_output_params = FstOutputParams()
		self.add_param('%s:fst_output_params:SumPrint'%(firstname), val=False)
		self.add_param('%s:fst_output_params:SttsTime'%(firstname), val=0.)
		self.add_param('%s:fst_output_params:ChkptTime'%(firstname), val=0.)
		self.add_param('%s:fst_output_params:DT_Out'%(firstname), val=0.)
		self.add_param('%s:fst_output_params:OutFileFmt'%(firstname), val=0)
		self.add_param('%s:fst_output_params:TabDelim'%(firstname), val=False)
		self.add_param('%s:fst_output_params:OutFmt'%(firstname), val='')

		#self.visualization = Visualization()
		self.add_param('%s:visualization:WrVTK'%(firstname), val=0)
		self.add_param('%s:visualization:VTK_type'%(firstname), val=0)
		self.add_param('%s:visualization:VTK_fields'%(firstname), val=0)
		self.add_param('%s:visualization:VTK_fps'%(firstname), val=0)

                #self.linearization = Linearization()
                self.add_param('%s:linearization:Linearize'%(firstname), val=False)
                self.add_param('%s:linearization:NLinTimes'%(firstname), val=2)
                self.add_param('%s:linearization:LinTimes'%(firstname), val=(30, 60))
                self.add_param('%s:linearization:LinInputs'%(firstname), val=1)
                self.add_param('%s:linearization:LinOutputs'%(firstname), val=1)
                self.add_param('%s:linearization:LinOutJac'%(firstname), val=False)
                self.add_param('%s:linearization:LinOutMod'%(firstname), val=False)

                ###################
		# Elastodyn vartrees
                ###################
		#self.ed_sim_ctrl = EdSimCtrl()
		self.add_param('%s:ed_sim_ctrl:Echo'%(firstname), val=False)
		self.add_param('%s:ed_sim_ctrl:Method'%(firstname), val=0)
		self.add_param('%s:ed_sim_ctrl:DT'%(firstname), val=0.)

		#self.envir_cond = EnvirCond()
		self.add_param('%s:envir_cond:Gravity'%(firstname), val=0.)

		#self.dof = DOF()
		self.add_param('%s:dof:FlapDOF1'%(firstname), val=False)
		self.add_param('%s:dof:FlapDOF2'%(firstname), val=False)
		self.add_param('%s:dof:EdgeDOF'%(firstname), val=False)
		self.add_param('%s:dof:TeetDOF'%(firstname), val=False)
		self.add_param('%s:dof:DrTrDOF'%(firstname), val=False)
		self.add_param('%s:dof:GenDOF'%(firstname), val=False)
		self.add_param('%s:dof:YawDOF'%(firstname), val=False)
		self.add_param('%s:dof:TwFADOF1'%(firstname), val=False)
		self.add_param('%s:dof:TwFADOF2'%(firstname), val=False)
		self.add_param('%s:dof:TwSSDOF1'%(firstname), val=False)
		self.add_param('%s:dof:TwSSDOF2'%(firstname), val=False)
		self.add_param('%s:dof:PtfmSgDOF'%(firstname), val=False)
		self.add_param('%s:dof:PtfmSwDOF'%(firstname), val=False)
		self.add_param('%s:dof:PtfmHvDOF'%(firstname), val=False)
		self.add_param('%s:dof:PtfmRDOF'%(firstname), val=False)
		self.add_param('%s:dof:PtfmPDOF'%(firstname), val=False)
		self.add_param('%s:dof:PtfmYDOF'%(firstname), val=False)

		#self.init_conds = InitConds()
		self.add_param('%s:init_conds:OoPDefl'%(firstname), val=0.0)
		self.add_param('%s:init_conds:IPDefl'%(firstname), val=0.0)
		self.add_param('%s:init_conds:BlPitch1'%(firstname), val=0.0)
		self.add_param('%s:init_conds:BlPitch2'%(firstname), val=0.0)
		self.add_param('%s:init_conds:BlPitch3'%(firstname), val=0.0)
		self.add_param('%s:init_conds:TeetDefl'%(firstname), val=0.0)
		self.add_param('%s:init_conds:Azimuth'%(firstname), val=0.0)
		self.add_param('%s:init_conds:RotSpeed'%(firstname), val=0.0)
		self.add_param('%s:init_conds:NacYaw'%(firstname), val=0.0)
		self.add_param('%s:init_conds:TTDspFA'%(firstname), val=0.0)
		self.add_param('%s:init_conds:TTDspSS'%(firstname), val=0.0)
		self.add_param('%s:init_conds:PtfmSurge'%(firstname), val=0.0)
		self.add_param('%s:init_conds:PtfmHeave'%(firstname), val=0.0)
		self.add_param('%s:init_conds:PtfmRoll'%(firstname), val=0.0)
		self.add_param('%s:init_conds:PtfmPitch'%(firstname), val=0.0)
		self.add_param('%s:init_conds:PtfmYaw'%(firstname), val=0.0)

		#self.turb_config = TurbConfig()
		self.add_param('%s:turb_config:NumBl'%(firstname), val=0)
		self.add_param('%s:turb_config:TipRad'%(firstname), val=0.)
		self.add_param('%s:turb_config:HubRad'%(firstname), val=0.)
		self.add_param('%s:turb_config:PreCone1'%(firstname), val=0.)
		self.add_param('%s:turb_config:PreCone2'%(firstname), val=0.)
		self.add_param('%s:turb_config:PreCone3'%(firstname), val=0.)
		self.add_param('%s:turb_config:HubCM'%(firstname), val=0.)
		self.add_param('%s:turb_config:UndSling'%(firstname), val=0.)
		self.add_param('%s:turb_config:Delta3'%(firstname), val=0.)
		self.add_param('%s:turb_config:AzimB1Up'%(firstname), val=0.)
		self.add_param('%s:turb_config:OverHang'%(firstname), val=0.)
		self.add_param('%s:turb_config:ShftGagL'%(firstname), val=0.)
		self.add_param('%s:turb_config:ShftTilt'%(firstname), val=0.)
		self.add_param('%s:turb_config:NacCMxn'%(firstname), val=0.)
		self.add_param('%s:turb_config:NacCMyn'%(firstname), val=0.)
		self.add_param('%s:turb_config:NacCMzn'%(firstname), val=0.)
		self.add_param('%s:turb_config:NcIMUxn'%(firstname), val=0.)
		self.add_param('%s:turb_config:NcIMUyn'%(firstname), val=0.)
		self.add_param('%s:turb_config:NcIMUzn'%(firstname), val=0.)
		self.add_param('%s:turb_config:Twr2Shft'%(firstname), val=0.)
		self.add_param('%s:turb_config:TowerHt'%(firstname), val=0.)
		self.add_param('%s:turb_config:TowerBsHt'%(firstname), val=0.)
		self.add_param('%s:turb_config:PtfmCMxt'%(firstname), val=0.)
		self.add_param('%s:turb_config:PtfmCMyt'%(firstname), val=0.)
		self.add_param('%s:turb_config:PtfmCMzt'%(firstname), val=0.)
		self.add_param('%s:turb_config:PtfmRefzt'%(firstname), val=0.)

		#self.mass_inertia = MassInertia()
		self.add_param('%s:mass_inertia:TipMass1'%(firstname), val=0.)
		self.add_param('%s:mass_inertia:TipMass2'%(firstname), val=0.)
		self.add_param('%s:mass_inertia:HubMass'%(firstname), val=0.)
		self.add_param('%s:mass_inertia:HubIner'%(firstname), val=0.)
		self.add_param('%s:mass_inertia:GenIner'%(firstname), val=0.)
		self.add_param('%s:mass_inertia:NacMass'%(firstname), val=0.)
		self.add_param('%s:mass_inertia:NacYIner'%(firstname), val=0.)
		self.add_param('%s:mass_inertia:YawBrMass'%(firstname), val=0.)
		self.add_param('%s:mass_inertia:PtfmMass'%(firstname), val=0.)
		self.add_param('%s:mass_inertia:PtfmRIner'%(firstname), val=0.)
		self.add_param('%s:mass_inertia:PtfmPIner'%(firstname), val=0.)
		self.add_param('%s:mass_inertia:PtfmYIner'%(firstname), val=0.)

		#self.blade_struc = BladeStruc()
		self.add_param('%s:blade_struc:BldNodes'%(firstname), val=0)
		self.add_param('%s:blade_struc:BldFile1'%(firstname), val='')
		self.add_param('%s:blade_struc:BldFile2'%(firstname), val='')
		self.add_param('%s:blade_struc:BldFile3'%(firstname), val='')
		self.add_param('%s:blade_struc:NBlInpSt'%(firstname), val=0)
		self.add_param('%s:blade_struc:CalcBMode'%(firstname), val=False)
		self.add_param('%s:blade_struc:BldFlDmp1'%(firstname), val=0.)
		self.add_param('%s:blade_struc:BldFlDmp2'%(firstname), val=0.)
		self.add_param('%s:blade_struc:BldEdDmp1'%(firstname), val=0.)
		self.add_param('%s:blade_struc:FlStTunr1'%(firstname), val=0.)
		self.add_param('%s:blade_struc:FlStTunr2'%(firstname), val=0.)
		self.add_param('%s:blade_struc:AdjBlMs'%(firstname), val=0.)
		self.add_param('%s:blade_struc:AdjFlSt'%(firstname), val=0.)
		self.add_param('%s:blade_struc:AdjEdSt'%(firstname), val=0.)
		self.add_param('%s:blade_struc:BlFract'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:AeroCent'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:PitchAxis'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:StrcTwst'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:BMassDen'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:FlpStff'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:EdgStff'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:GJStff'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:EAStff'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:Alpha'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:FlpIner'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:EdgIner'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:PrecrvRef'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:PreswpRef'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:FlpcgOf'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:Edgcgof'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:FlpEAOf'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:EdgEAOf'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:BldFl1Sh'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:BldFl2Sh'%(firstname), zeros([1]))
		self.add_param('%s:blade_struc:BldEdgSh'%(firstname), zeros([1]))

		#self.rotor_teeter = RotorT:eter()
		self.add_param('%s:rotor_teeter:TeetMod'%(firstname), val=0)
		self.add_param('%s:rotor_teeter:TeetDmpP'%(firstname), val=0.0)
		self.add_param('%s:rotor_teeter:TeetDmp'%(firstname), val=0.0)
		self.add_param('%s:rotor_teeter:TeetCDmp'%(firstname), val=0.0)
		self.add_param('%s:rotor_teeter:TeetSStP'%(firstname), val=0.0)
		self.add_param('%s:rotor_teeter:TeetHStP'%(firstname), val=0.0)
		self.add_param('%s:rotor_teeter:TeetSSSp'%(firstname), val=0.0)
		self.add_param('%s:rotor_teeter:TeetHSSp'%(firstname), val=0.0)

		#self.drivetrain = DriveTrai:()
		self.add_param('%s:drivetrain:GBoxEff'%(firstname), val=0.0)
		self.add_param('%s:drivetrain:GBRatio'%(firstname), val=0.0)
		self.add_param('%s:drivetrain:DTTorSpr'%(firstname), val=0.0)
		self.add_param('%s:drivetrain:DTTorDmp'%(firstname), val=0.0)
		self.add_param('%s:drivetrain:GBRevers'%(firstname), val=0.0)
		self.add_param('%s:drivetrain:DynBrkFi'%(firstname), val=0.0)

		#self.furling = Furling()
		self.add_param('%s:furling:Furling'%(firstname), val=False)
		self.add_param('%s:furling:FurlFile'%(firstname), val='')

		#self.platform = Platform()
		self.add_param('%s:platform:PtfmModel'%(firstname), val=0)
		self.add_param('%s:platform:PtfmFile'%(firstname), val='')

		#self.tower = Tower()
		self.add_param('%s:tower:TwrNodes'%(firstname), val=0)
		self.add_param('%s:tower:TwrFile'%(firstname), val='')
		self.add_param('%s:tower:NTwInptSt'%(firstname), val=0)
		self.add_param('%s:tower:CalcTMode'%(firstname), val=False)
		self.add_param('%s:tower:TwrFADmp1'%(firstname), val=0.)
		self.add_param('%s:tower:TwrFADmp2'%(firstname), val=0.)
		self.add_param('%s:towSr:TwrSSDmp1'%(firstname), val=0.)
		self.add_param('%s:towSr:TwrSSDmp2'%(firstname), val=0.)
		self.add_param('%s:towSr:FAStTunr1'%(firstname), val=0.)
		self.add_param('%s:towSr:FAStTunr2'%(firstname), val=0.)
		self.add_param('%s:towSr:SSStTunr1'%(firstname), val=0.)
		self.add_param('%s:towSr:SSStTunr2'%(firstname), val=0.)
		self.add_param('%s:towSr:AdjTwMa'%(firstname), val=0.)
		self.add_param('%s:towSr:AdjFASt'%(firstname), val=0.)
		self.add_param('%s:towSr:AdjSSSt'%(firstname), val=0.)
		self.add_param('%s:towSr:HtFract'%(firstname), val=zeros([1]))
		self.add_param('%s:towSr:TMassDen'%(firstname), val=zeros([1]))
		self.add_param('%s:towSr:TwFAStif'%(firstname), val=zeros([1]))
		self.add_param('%s:towSr:TwSSStif'%(firstname), val=zeros([1]))
		self.add_param('%s:towSr:TwGJStif'%(firstname), val=zeros([1]))
		self.add_param('%s:towSr:TwEAStif'%(firstname), val=zeros([1]))
		self.add_param('%s:towSr:TwFAIner'%(firstname), val=zeros([1]))
		self.add_param('%s:towSr:TwSSIner'%(firstname), val=zeros([1]))
		self.add_param('%s:towSr:TwFAcgOf'%(firstname), val=zeros([1]))
		self.add_param('%s:towSr:TwSScgOf'%(firstname), val=zeros([1]))
		self.add_param('%s:towSr:TwFAM1Sh'%(firstname), val=zeros([1]))
		self.add_param('%s:towSr:TwFAM2Sh'%(firstname), val=zeros([1]))
		self.add_param('%s:towSr:TwSSM1Sh'%(firstname), val=zeros([1]))
		self.add_param('%s:towSr:TwSSM2Sh'%(firstname), val=zeros([1]))

		#self.ed_out_params = EdOutParams()
		self.add_param('%s:ed_out_params:SumPrint'%(firstname), val=False)
		self.add_param('%s:ed_out_params:OutFile'%(firstname), val=0)
		self.add_param('%s:ed_out_params:TabDelim'%(firstname), val=False)
		self.add_param('%s:ed_out_params:OutFmt'%(firstname), val='')
		self.add_param('%s:ed_out_params:TStart'%(firstname), val=0.0)
		self.add_param('%s:ed_out_params:DecFact'%(firstname), val=0.0)
		self.add_param('%s:ed_out_params:NTwGages'%(firstname), val=0)
		self.add_param('%s:ed_out_params:TwrGagNd'%(firstname), val=[])
		self.add_param('%s:ed_out_params:NBlGages'%(firstname), val=0)
		self.add_param('%s:ed_out_params:BldGagNd'%(firstname), val=[])

                ##################:
		# Wind vartrees
                ###################
		#self.inflow_wind = InflowWind()
		self.add_param('%s:inflow_wind:Echo'%(firstname), val=False)
		self.add_param('%s:inflow_wind:WindType'%(firstname), val=0)
		self.add_param('%s:inflow_wind:PropagationDir'%(firstname), val=0.)
		self.add_param('%s:inflow_wind:NWindVel'%(firstname), val=0)
		self.add_param('%s:inflow_wind:WindVxiList'%(firstname), val=0.)
		self.add_param('%s:inflow_wind:WindVyiList'%(firstname), val=0.)
		self.add_param('%s:inflow_wind:WindVziList'%(firstname), val=0.)

		#self.steady_wind_params = SteadyWindParams()
		self.add_param('%s:steady_wind_params:HWindSpeed'%(firstname), val=0.)
		self.add_param('%s:steady_wind_params:RefHt'%(firstname), val=0.)
		self.add_param('%s:steady_wind_params:PLexp'%(firstname), val=0.)

		#self.uniform_wind_params = UniformWindParams()
		self.add_param('%s:uniform_wind_params:Filename'%(firstname), val='')
		self.add_param('%s:uniform_wind_params:RefHt'%(firstname), val=0.)
		self.add_param('%s:uniform_wind_params:RefLength'%(firstname), val=0.)

		#self.turbsim_wind_params = TurbSimWindParams()
		self.add_param('%s:turbsim_wind_params:Filename'%(firstname), val='')

		#self.bladed_wind_params = BladedWindParams()
		self.add_param('%s:bladed_wind_params:FilenameRoot'%(firstname), val='')
		self.add_param('%s:bladed_wind_params:TowerFile'%(firstname), val=False)

		#self.hawc_wind_params = HAWCWindParams()
		self.add_param('%s:hawc_wind_params:FileName_u'%(firstname), val='')
		self.add_param('%s:hawc_wind_params:FileName_v'%(firstname), val='')
		self.add_param('%s:hawc_wind_params:FileName_w'%(firstname), val='')
		self.add_param('%s:hawc_wind_params:nx'%(firstname), val=0)
		self.add_param('%s:hawc_wind_params:ny'%(firstname), val=0)
		self.add_param('%s:hawc_wind_params:nz'%(firstname), val=0)
		self.add_param('%s:hawc_wind_params:dx'%(firstname), val=0.)
		self.add_param('%s:hawc_wind_params:dy'%(firstname), val=0.)
		self.add_param('%s:hawc_wind_params:dz'%(firstname), val=0.)
		self.add_param('%s:hawc_wind_params:RefHt'%(firstname), val=0.)
		self.add_param('%s:hawc_wind_params:ScaleMethod'%(firstname), val=0)
		self.add_param('%s:hawc_wind_params:SFx'%(firstname), val=0.)
		self.add_param('%s:hawc_wind_params:SFy'%(firstname), val=0.)
		self.add_param('%s:hawc_wind_params:SFz'%(firstname), val=0.)
		self.add_param('%s:hawc_wind_params:SigmaFx'%(firstname), val=0.)
		self.add_param('%s:hawc_wind_params:SigmaFy'%(firstname), val=0.)
		self.add_param('%s:hawc_wind_params:SigmaFz'%(firstname), val=0.)
		self.add_param('%s:hawc_wind_params:URef'%(firstname), val=0.)
		self.add_param('%s:hawc_wind_params:WindProfile'%(firstname), val=0)
		self.add_param('%s:hawc_wind_params:PLExp'%(firstname), val=0.)
		self.add_param('%s:hawc_wind_params:Z0'%(firstname), val=0.)


		#self.inflow_out_params = Inflow:utParams()
		self.add_param('%s:inflow_out_params:SumPrint'%(firstname), val=False)

		#self.wnd_wind = WndWind()
		self.add_param('%s:wnd_wind:TimeSteps'%(firstname), val=0)
		self.add_param('%s:wnd_wind:Time'%(firstname), val=zeros([1]))
		self.add_param('%s:wnd_wind:HorSpd'%(firstname), val=zeros([1]))
		self.add_param('%s:wnd_wind:WindDir'%(firstname), val=zeros([1]))
		self.add_param('%s:wnd_wind:VerSpd'%(firstname), val=zeros([1]))
		self.add_param('%s:wnd_wind:HorShr'%(firstname), val=zeros([1]))
		self.add_param('%s:wnd_wind:VerShr'%(firstname), val=zeros([1]))
		self.add_param('%s:wnd_wind:LnVShr'%(firstname), val=zeros([1]))
		self.add_param('%s:wnd_wind:GstSpd'%(firstname), val=zeros([1]))

                ###################
		# AeroDyn vartrees
                ###################
		#self.aerodyn = AeroDyn()
		self.add_param('%s:aerodyn:SysUnits'%(firstname), val='SI')
		self.add_param('%s:aerodyn:StallMod'%(firstname), val='BEDOES')
		self.add_param('%s:aerodyn:UseCM'%(firstname), val='NO_CM')
		self.add_param('%s:aerodyn:InfModel'%(firstname), val='EQUIL')
		self.add_param('%s:aerodyn:IndModel'%(firstname), val='SWIRL')
		self.add_param('%s:aerodyn:AToler'%(firstname), val=0.)
		self.add_param('%s:aerodyn:TLModel'%(firstname), val='PRANDtl')
		self.add_param('%s:aerodyn:HLModel'%(firstname), val='PRANDTl')
		self.add_param('%s:aerodyn:WindFile'%(firstname), val='')
		self.add_param('%s:aerodyn:wind_file_type'%(firstname), val='hh')
		self.add_param('%s:aerodyn:HH'%(firstname), val=0.)
		self.add_param('%s:aerodyn:TwrShad'%(firstname), val=0.)
		self.add_param('%s:aerodyn:ShadHWid'%(firstname), val=9999.9)
		self.add_param('%s:aerodyn:T_Shad_Refpt'%(firstname), val=9999.9)
		self.add_param('%s:aerodyn:AirDens'%(firstname), val=1.225)
		self.add_param('%s:aerodyn:KinVisc'%(firstname), val=1.464e-5)
		self.add_param('%s:aerodyn:DTAero'%(firstname), val=0.02479)

		#self.blade_aero = AeroDynBlade()
		self.add_param('%s:blade_aero:NumFoil'%(firstname), val=0)
		self.add_param('%s:blade_aero:FoilNm'%(firstname), val=zeros([1]))
		self.add_param('%s:blade_aero:af_data'%(firstname), val=[])
		self.add_param('%s:blade_aero:BldNodes'%(firstname), val=zeros([1]))
		self.add_param('%s:blade_aero:AeroTwst'%(firstname), val=zeros([1]))
		self.add_param('%s:blade_aero:DRNodes'%(firstname), val=zeros([1]))
		self.add_param('%s:blade_aero:Chord'%(firstname), val=zeros([1]))
		self.add_param('%s:blade_aero:NFoil'%(firstname), val=zeros([1]))
		self.add_param('%s:blade_aero:PrnElm'%(firstname), val=zeros([1]))

                ###################
		# ServoDyn vartrees
                ###################
		#self.sd_sim_ctrl = SdSimCtrl()
		self.add_param('%s:sd_sim_ctrl:Echo'%(firstname), val=False)
		self.add_param('%s:sd_sim_ctrl:DT'%(firstname), val=0.)
                
		#self.pitch_ctrl = PitchCtrl()
		self.add_param('%s:pitch_ctrl:PCMode'%(firstname), val=0)
		self.add_param('%s:pitch_ctrl:TPCOn'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:TPitManS1'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:TPitManS2'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:TPitManS3'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:TPitManE1'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:TPitManE2'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:TPitManE3'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:PitManRat1'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:PitManRat2'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:PitManRat3'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:BlPitchF1'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:BlPitchF2'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:BlPitchF3'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:BlPitch1'%(firstname), val=0.)
		self.add_param('%s:pitch_ctrl:BlPitch2'%(firstname), val=0.)

		#self.gen_torq_ctrl = GenTorqCtrl()
		self.add_param('%s:gen_torq_ctrl:VSContrl'%(firstname), val=0)
		self.add_param('%s:gen_torq_ctrl:GenModel'%(firstname), val=0)
		self.add_param('%s:gen_torq_ctrl:GenEff'%(firstname), val=0.)
		self.add_param('%s:gen_torq_ctrl:GenTiStr'%(firstname), val=False)
		self.add_param('%s:gen_torq_ctrl:GenTiStp'%(firstname), val=False)
		self.add_param('%s:gen_torq_ctrl:SpdGenOn'%(firstname), val=0.)
		self.add_param('%s:gen_torq_ctrl:TimGenOn'%(firstname), val=0.)
		self.add_param('%s:gen_torq_ctrl:TimGenOf'%(firstname), val=0.)

		#self.var_speed_torq_ctrl = VarSpeedTorqCtrl()
                self.add_param('%s:var_speed_torq_ctrl:VS_RtGnSp'%(firstname), val=0.)
                self.add_param('%s:var_speed_torq_ctrl:VS_RtTq'%(firstname), val=0.)
                self.add_param('%s:var_speed_torq_ctrl:VS_Rgn2K'%(firstname), val=0.)
                self.add_param('%s:var_speed_torq_ctrl:VS_SlPc'%(firstname), val=0.)

		#self.induct_gen = InductGen()
		self.add_param('%s:induct_gen:SIG_SlPc'%(firstname), val=0.)
		self.add_param('%s:induct_gen:SIG_SySp'%(firstname), val=0.)
		self.add_param('%s:induct_gen:SIG_RtTq'%(firstname), val=0.)
		self.add_param('%s:induct_gen:SIG_PORt'%(firstname), val=0.)

		#self.theveq_induct_gen = ThevEqInductGen()
		self.add_param('%s:theveq_induct_gen:TEC_Freq'%(firstname), val=0.)
		self.add_param('%s:theveq_induct_gen:TEC_NPol'%(firstname), val=0)
		self.add_param('%s:theveq_induct_gen:TEC_SRes'%(firstname), val=0.)
		self.add_param('%s:theveq_induct_gen:TEC_RRes'%(firstname), val=0.)
		self.add_param('%s:theveq_induct_gen:TEC_VLL'%(firstname), val=0.)
		self.add_param('%s:theveq_induct_gen:TEC_SLR'%(firstname), val=0.)
		self.add_param('%s:theveq_induct_gen:TEC_RLR'%(firstname), val=0.)
		self.add_param('%s:theveq_induct_gen:TEC_MR'%(firstname), val=0.)

		#self.shaft_brake = ShaftBrake()
		self.add_param('%s:shaft_brake:HSSBrMode'%(firstname), val=0)
		self.add_param('%s:shaft_brake:THSSBrDp'%(firstname), val=0.)
		self.add_param('%s:shaft_brake:HSSBrDT'%(firstname), val=0.)
		self.add_param('%s:shaft_brake:HSSBrTqF'%(firstname), val=0.)

		#self.nac_yaw_ctrl = NacYawCtrl()
		self.add_param('%s:nac_yaw_ctrl:YCMode'%(firstname), val=0)
		self.add_param('%s:nac_yaw_ctrl:TYCOn'%(firstname), val=0.)
		self.add_param('%s:nac_yaw_ctrl:YawNeut'%(firstname), val=0.)
		self.add_param('%s:nac_yaw_ctrl:YawSpr'%(firstname), val=0.)
		self.add_param('%s:nac_yaw_ctrl:YawDamp'%(firstname), val=0.)
		self.add_param('%s:nac_yaw_ctrl:TYawManS'%(firstname), val=0.)
		self.add_param('%s:nac_yaw_ctrl:YawManRat'%(firstname), val=0.)
		self.add_param('%s:nac_yaw_ctrl:NacYawF'%(firstname), val=0.)

		#self.tip_brake = TipBrake()
		self.add_param('%s:tip_brake:TiDynBrk'%(firstname), val=0.)
		self.add_param('%s:tip_brake:TTpBrDp1'%(firstname), val=0.)
		self.add_param('%s:tip_brake:TTpBrDp2'%(firstname), val=0.)
		self.add_param('%s:tip_brake:TTpBrDp3'%(firstname), val=0.)
		self.add_param('%s:tip_brake:TBDepISp1'%(firstname), val=0.)
		self.add_param('%s:tip_brake:TBDepISp2'%(firstname), val=0.)
		self.add_param('%s:tip_brake:TBDepISp3'%(firstname), val=0.)
		self.add_param('%s:tip_brake:TBDrConN'%(firstname), val=0.)
		self.add_param('%s:tip_brake:TBDrConD'%(firstname), val=0.)
		self.add_param('%s:tip_brake:TpBrDT'%(firstname), val=0.)

		#self.tuned_mass_damper = TunedMassDamp()
		self.add_param('%s:tuned_mass_damper:CompNTMD'%(firstname), val=0.)
		self.add_param('%s:tuned_mass_damper:NTMDfile'%(firstname), val='')
		self.add_param('%s:tuned_mass_damper:CompTTMD'%(firstname), val=0.)
		self.add_param('%s:tuned_mass_damper:TTMDfile'%(firstname), val='')

		#self.bladed_interface = BladedInterface()
		self.add_param('%s:bladed_interface:DLL_FileName'%(firstname), val='')
		self.add_param('%s:bladed_interface:DLL_InFile'%(firstname), val='')
		self.add_param('%s:bladed_interface:DLL_ProcName'%(firstname), val='')
		self.add_param('%s:bladed_interface:DLL_DT'%(firstname), val='')
		self.add_param('%s:bladed_interface:DLL_Ramp'%(firstname), val=False)
		self.add_param('%s:bladed_interface:BPCutoff'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:NacYaw_North'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:Ptch_Cntrl'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:Ptch_SetPnt'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:Ptch_Min'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:Ptch_Max'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:PtchRate_Min'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:PtchRate_Max'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:Gain_OM'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:GenSpd_MinOM'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:GenSpd_MaxOM'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:GenSpd_Dem'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:GenPwr_Dem'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:DLL_NumTrq'%(firstname), val=0.)
		self.add_param('%s:bladed_interface:GenSpd_TLU'%(firstname), val=zeros([0]))
		self.add_param('%s:bladed_interface:GenTrq_TLU'%(firstname), val=zeros([0]))

		#self.sd_out_params = SdOutParams()
		self.add_param('%s:sd_out_params:SumPrint'%(firstname), val=False)
		self.add_param('%s:sd_out_params:OutFile'%(firstname), val=0)
		self.add_param('%s:sd_out_params:TabDelim'%(firstname), val=False)
		self.add_param('%s:sd_out_params:OutFmt'%(firstname), val='')
		self.add_param('%s:sd_out_params:TStart'%(firstname), val=0.)
		
		# List of Outputs (all input files -- FST, ED, SD)
		# TODO: Update FstOutput for a few new outputs in FAST8
		#self.outlist = FstOutput()   # 
		self.add_param('%s:outlist:description'%(firstname), val='')











