#from openmdao.api import Component
from numpy import zeros
def FstModel(self):
	#def __init__(self):%i:
                super(FstModel,self).__init__()

		# Description
		self.add_param('description'%i, val='')

                ###################
		# Fst file vartrees
                ###################

		#self.fst_sim_ctrl = FstSimCtrl()
		self.add_param('fst_sim_ctrl:%i:Echo'%i, val=False)
		self.add_param('fst_sim_ctrl:%i:AbortLevel'%i, val='')
		self.add_param('fst_sim_ctrl:%i:TMax'%i, val=0.)
		self.add_param('fst_sim_ctrl:%i:DT'%i, val=0.)
		self.add_param('fst_sim_ctrl:%i:InterpOrder'%i, val=0)
		self.add_param('fst_sim_ctrl:%i:NumCrctn'%i, val=0)
		self.add_param('fst_sim_ctrl:%i:DT_UJac'%i, val=0.)
		self.add_param('fst_sim_ctrl:%i:UJacSclFact'%i, val=0.)
		self.add_param('fst_sim_ctrl:%i:ADAMSPrep'%i, val=0)
		self.add_param('fst_sim_ctrl:%i:AnalMode'%i, val=0)

		#self.ftr_swtchs_flgs = FtrSwtchsFlgs()
		self.add_param('ftr_swtchs_flgs:%i:CompElast'%i, val=0)
		self.add_param('ftr_swtchs_flgs:%i:CompInflow'%i, val=0)
		self.add_param('ftr_swtchs_flgs:%i:CompAero'%i, val=0)
		self.add_param('ftr_swtchs_flgs:%i:CompServo'%i, val=0)
		self.add_param('ftr_swtchs_flgs:%i:CompHydro'%i, val=0)
		self.add_param('ftr_swtchs_flgs:%i:CompSub'%i, val=0)
		self.add_param('ftr_swtchs_flgs:%i:CompMooring'%i, val=0)
		self.add_param('ftr_swtchs_flgs:%i:CompIce'%i, val=0)
		self.add_param('ftr_swtchs_flgs:%i:CompNoise'%i, val=0)

		#self.input_files = InputFiles()
		self.add_param('input_files:%i:EDFile'%i, val='')
		self.add_param('input_files:%i:BDBldFile1'%i, val='')
		self.add_param('input_files:%i:BDBldFile2'%i, val='')
		self.add_param('input_files:%i:BDBldFile3'%i, val='')
		self.add_param('input_files:%i:InflowFile'%i, val='')
		self.add_param('input_files:%i:AeroFile'%i, val='')
		self.add_param('input_files:%i:ServoFile'%i, val='')
		self.add_param('input_files:%i:HydroFile'%i, val='')
		self.add_param('input_files:%i:SubFile'%i, val='')
		self.add_param('input_files:%i:MooringFile'%i, val='')
		self.add_param('input_files:%i:IceFile'%i, val='')
		self.add_param('input_files:%i:ADFile'%i, val='')
		self.add_param('input_files:%i:NoiseFile'%i, val='')
		self.add_param('input_files:%i:ADAMSFile'%i, val='')
		self.add_param('input_files:%i:LinFile'%i, val='')
               
		#self.fst_output_params = FstOutputParams()
		self.add_param('fst_output_params:%i:SumPrint'%i, val=False)
		self.add_param('fst_output_params:%i:SttsTime'%i, val=0.)
		self.add_param('fst_output_params:%i:ChkptTime'%i, val=0.)
		self.add_param('fst_output_params:%i:DT_Out'%i, val=0.)
		self.add_param('fst_output_params:%i:OutFileFmt'%i, val=0)
		self.add_param('fst_output_params:%i:TabDelim'%i, val=False)
		self.add_param('fst_output_params:%i:OutFmt'%i, val='')

		#self.visualization = Visualization()
		self.add_param('visualization:%i:WrVTK'%i, val=0)
		self.add_param('visualization:%i:VTK_type'%i, val=0)
		self.add_param('visualization:%i:VTK_fields'%i, val=0)
		self.add_param('visualization:%i:VTK_fps'%i, val=0)

                #self.linearization = Linearization()
                self.add_param('linearization:%i:Linearize'%i, val=False)
                self.add_param('linearization:%i:NLinTimes'%i, val=2)
                self.add_param('linearization:%i:LinTimes'%i, val=(30, 60))
                self.add_param('linearization:%i:LinInputs'%i, val=1)
                self.add_param('linearization:%i:LinOutputs'%i, val=1)
                self.add_param('linearization:%i:LinOutJac'%i, val=False)
                self.add_param('linearization:%i:LinOutMod'%i, val=False)

                ###################
		# Elastodyn vartrees
                ###################
		#self.ed_sim_ctrl = EdSimCtrl()
		self.add_param('ed_sim_ctrl:%i:Echo'%i, val=False)
		self.add_param('ed_sim_ctrl:%i:Method'%i, val=0)
		self.add_param('ed_sim_ctrl:%i:DT'%i, val=0.)

		#self.envir_cond = EnvirCond()
		self.add_param('envir_cond:%i:Gravity'%i, val=0.)

		#self.dof = DOF()
		self.add_param('dof:%i:FlapDOF1'%i, val=False)
		self.add_param('dof:%i:FlapDOF2'%i, val=False)
		self.add_param('dof:%i:EdgeDOF'%i, val=False)
		self.add_param('dof:%i:TeetDOF'%i, val=False)
		self.add_param('dof:%i:DrTrDOF'%i, val=False)
		self.add_param('dof:%i:GenDOF'%i, val=False)
		self.add_param('dof:%i:YawDOF'%i, val=False)
		self.add_param('dof:%i:TwFADOF1'%i, val=False)
		self.add_param('dof:%i:TwFADOF2'%i, val=False)
		self.add_param('dof:%i:TwSSDOF1'%i, val=False)
		self.add_param('dof:%i:TwSSDOF2'%i, val=False)
		self.add_param('dof:%i:PtfmSgDOF'%i, val=False)
		self.add_param('dof:%i:PtfmSwDOF'%i, val=False)
		self.add_param('dof:%i:PtfmHvDOF'%i, val=False)
		self.add_param('dof:%i:PtfmRDOF'%i, val=False)
		self.add_param('dof:%i:PtfmPDOF'%i, val=False)
		self.add_param('dof:%i:PtfmYDOF'%i, val=False)

		#self.init_conds = InitConds()
		self.add_param('init_conds:%i:OoPDefl'%i, val=0.0)
		self.add_param('init_conds:%i:IPDefl'%i, val=0.0)
		self.add_param('init_conds:%i:BlPitch1'%i, val=0.0)
		self.add_param('init_conds:%i:BlPitch2'%i, val=0.0)
		self.add_param('init_conds:%i:BlPitch3'%i, val=0.0)
		self.add_param('init_conds:%i:TeetDefl'%i, val=0.0)
		self.add_param('init_conds:%i:Azimuth'%i, val=0.0)
		self.add_param('init_conds:%i:RotSpeed'%i, val=0.0)
		self.add_param('init_conds:%i:NacYaw'%i, val=0.0)
		self.add_param('init_conds:%i:TTDspFA'%i, val=0.0)
		self.add_param('init_conds:%i:TTDspSS'%i, val=0.0)
		self.add_param('init_conds:%i:PtfmSurge'%i, val=0.0)
		self.add_param('init_conds:%i:PtfmHeave'%i, val=0.0)
		self.add_param('init_conds:%i:PtfmRoll'%i, val=0.0)
		self.add_param('init_conds:%i:PtfmPitch'%i, val=0.0)
		self.add_param('init_conds:%i:PtfmYaw'%i, val=0.0)

		#self.turb_config = TurbConfig()
		self.add_param('turb_config:%i:NumBl'%i, val=0)
		self.add_param('turb_config:%i:TipRad'%i, val=0.)
		self.add_param('turb_config:%i:HubRad'%i, val=0.)
		self.add_param('turb_config:%i:PreCone1'%i, val=0.)
		self.add_param('turb_config:%i:PreCone2'%i, val=0.)
		self.add_param('turb_config:%i:PreCone3'%i, val=0.)
		self.add_param('turb_config:%i:HubCM'%i, val=0.)
		self.add_param('turb_config:%i:UndSling'%i, val=0.)
		self.add_param('turb_config:%i:Delta3'%i, val=0.)
		self.add_param('turb_config:%i:AzimB1Up'%i, val=0.)
		self.add_param('turb_config:%i:OverHang'%i, val=0.)
		self.add_param('turb_config:%i:ShftGagL'%i, val=0.)
		self.add_param('turb_config:%i:ShftTilt'%i, val=0.)
		self.add_param('turb_config:%i:NacCMxn'%i, val=0.)
		self.add_param('turb_config:%i:NacCMyn'%i, val=0.)
		self.add_param('turb_config:%i:NacCMzn'%i, val=0.)
		self.add_param('turb_config:%i:NcIMUxn'%i, val=0.)
		self.add_param('turb_config:%i:NcIMUyn'%i, val=0.)
		self.add_param('turb_config:%i:NcIMUzn'%i, val=0.)
		self.add_param('turb_config:%i:Twr2Shft'%i, val=0.)
		self.add_param('turb_config:%i:TowerHt'%i, val=0.)
		self.add_param('turb_config:%i:TowerBsHt'%i, val=0.)
		self.add_param('turb_config:%i:PtfmCMxt'%i, val=0.)
		self.add_param('turb_config:%i:PtfmCMyt'%i, val=0.)
		self.add_param('turb_config:%i:PtfmCMzt'%i, val=0.)
		self.add_param('turb_config:%i:PtfmRefzt'%i, val=0.)

		#self.mass_inertia = MassInertia()
		self.add_param('mass_inertia:%i:TipMass1'%i, val=0.)
		self.add_param('mass_inertia:%i:TipMass2'%i, val=0.)
		self.add_param('mass_inertia:%i:HubMass'%i, val=0.)
		self.add_param('mass_inertia:%i:HubIner'%i, val=0.)
		self.add_param('mass_inertia:%i:GenIner'%i, val=0.)
		self.add_param('mass_inertia:%i:NacMass'%i, val=0.)
		self.add_param('mass_inertia:%i:NacYIner'%i, val=0.)
		self.add_param('mass_inertia:%i:YawBrMass'%i, val=0.)
		self.add_param('mass_inertia:%i:PtfmMass'%i, val=0.)
		self.add_param('mass_inertia:%i:PtfmRIner'%i, val=0.)
		self.add_param('mass_inertia:%i:PtfmPIner'%i, val=0.)
		self.add_param('mass_inertia:%i:PtfmYIner'%i, val=0.)

		#self.blade_struc = BladeStruc()
		self.add_param('blade_struc:%i:BldNodes'%i, val=0)
		self.add_param('blade_struc:%i:BldFile1'%i, val='')
		self.add_param('blade_struc:%i:BldFile2'%i, val='')
		self.add_param('blade_struc:%i:BldFile3'%i, val='')
		self.add_param('blade_struc:%i:NBlInpSt'%i, val=0)
		self.add_param('blade_struc:%i:CalcBMode'%i, val=False)
		self.add_param('blade_struc:%i:BldFlDmp1'%i, val=0.)
		self.add_param('blade_struc:%i:BldFlDmp2'%i, val=0.)
		self.add_param('blade_struc:%i:BldEdDmp1'%i, val=0.)
		self.add_param('blade_struc:%i:FlStTunr1'%i, val=0.)
		self.add_param('blade_struc:%i:FlStTunr2'%i, val=0.)
		self.add_param('blade_struc:%i:AdjBlMs'%i, val=0.)
		self.add_param('blade_struc:%i:AdjFlSt'%i, val=0.)
		self.add_param('blade_struc:%i:AdjEdSt'%i, val=0.)
		self.add_param('blade_struc:%i:BlFract', zeros([1]))
		self.add_param('blade_struc:%i:AeroCent', zeros([1]))
		self.add_param('blade_struc:%i:PitchAxis', zeros([1]))
		self.add_param('blade_struc:%i:StrcTwst', zeros([1]))
		self.add_param('blade_struc:%i:BMassDen', zeros([1]))
		self.add_param('blade_struc:%i:FlpStff', zeros([1]))
		self.add_param('blade_struc:%i:EdgStff', zeros([1]))
		self.add_param('blade_struc:%i:GJStff', zeros([1]))
		self.add_param('blade_struc:%i:EAStff', zeros([1]))
		self.add_param('blade_struc:%i:Alpha', zeros([1]))
		self.add_param('blade_struc:%i:FlpIner', zeros([1]))
		self.add_param('blade_struc:%i:EdgIner', zeros([1]))
		self.add_param('blade_struc:%i:PrecrvRef', zeros([1]))
		self.add_param('blade_struc:%i:PreswpRef', zeros([1]))
		self.add_param('blade_struc:%i:FlpcgOf', zeros([1]))
		self.add_param('blade_struc:%i:Edgcgof', zeros([1]))
		self.add_param('blade_struc:%i:FlpEAOf', zeros([1]))
		self.add_param('blade_struc:%i:EdgEAOf', zeros([1]))
		self.add_param('blade_struc:%i:BldFl1Sh', zeros([1]))
		self.add_param('blade_struc:%i:BldFl2Sh', zeros([1]))
		self.add_param('blade_struc:%i:BldEdgSh', zeros([1]))

		#self.rotor_teeter = RotorT:%i:eter()
		self.add_param('rotor_teeter:%i:TeetMod'%i, val=0)
		self.add_param('rotor_teeter:%i:TeetDmpP'%i, val=0.0)
		self.add_param('rotor_teeter:%i:TeetDmp'%i, val=0.0)
		self.add_param('rotor_teeter:%i:TeetCDmp'%i, val=0.0)
		self.add_param('rotor_teeter:%i:TeetSStP'%i, val=0.0)
		self.add_param('rotor_teeter:%i:TeetHStP'%i, val=0.0)
		self.add_param('rotor_teeter:%i:TeetSSSp'%i, val=0.0)
		self.add_param('rotor_teeter:%i:TeetHSSp'%i, val=0.0)

		#self.drivetrain = DriveTrai:%i:()
		self.add_param('drivetrain:%i:GBoxEff'%i, val=0.0)
		self.add_param('drivetrain:%i:GBRatio'%i, val=0.0)
		self.add_param('drivetrain:%i:DTTorSpr'%i, val=0.0)
		self.add_param('drivetrain:%i:DTTorDmp'%i, val=0.0)
		self.add_param('drivetrain:%i:GBRevers'%i, val=0.0)
		self.add_param('drivetrain:%i:DynBrkFi'%i, val=0.0)

		#self.furling = Furling()
		self.add_param('furling:%i:Furling'%i, val=False)
		self.add_param('furling:%i:FurlFile'%i, val='')

		#self.platform = Platform()
		self.add_param('platform:%i:PtfmModel'%i, val=0)
		self.add_param('platform:%i:PtfmFile'%i, val='')

		#self.tower = Tower()
		self.add_param('tower:%i:TwrNodes'%i, val=0)
		self.add_param('tower:%i:TwrFile'%i, val='')
		self.add_param('tower:%i:NTwInptSt'%i, val=0)
		self.add_param('tower:%i:CalcTMode'%i, val=False)
		self.add_param('tower:%i:TwrFADmp1'%i, val=0.)
		self.add_param('tower:%i:TwrFADmp2'%i, val=0.)
		self.add_param('towSr:%i:TwrSSDmp1'%i, val=0.)
		self.add_param('towSr:%i:TwrSSDmp2'%i, val=0.)
		self.add_param('towSr:%i:FAStTunr1'%i, val=0.)
		self.add_param('towSr:%i:FAStTunr2'%i, val=0.)
		self.add_param('towSr:%i:SSStTunr1'%i, val=0.)
		self.add_param('towSr:%i:SSStTunr2'%i, val=0.)
		self.add_param('towSr:%i:AdjTwMa'%i, val=0.)
		self.add_param('towSr:%i:AdjFASt'%i, val=0.)
		self.add_param('towSr:%i:AdjSSSt'%i, val=0.)
		self.add_param('towSr:%i:HtFract'%i, val=zeros([1]))
		self.add_param('towSr:%i:TMassDen'%i, val=zeros([1]))
		self.add_param('towSr:%i:TwFAStif'%i, val=zeros([1]))
		self.add_param('towSr:%i:TwSSStif'%i, val=zeros([1]))
		self.add_param('towSr:%i:TwGJStif'%i, val=zeros([1]))
		self.add_param('towSr:%i:TwEAStif'%i, val=zeros([1]))
		self.add_param('towSr:%i:TwFAIner'%i, val=zeros([1]))
		self.add_param('towSr:%i:TwSSIner'%i, val=zeros([1]))
		self.add_param('towSr:%i:TwFAcgOf'%i, val=zeros([1]))
		self.add_param('towSr:%i:TwSScgOf'%i, val=zeros([1]))
		self.add_param('towSr:%i:TwFAM1Sh'%i, val=zeros([1]))
		self.add_param('towSr:%i:TwFAM2Sh'%i, val=zeros([1]))
		self.add_param('towSr:%i:TwSSM1Sh'%i, val=zeros([1]))
		self.add_param('towSr:%i:TwSSM2Sh'%i, val=zeros([1]))

		#self.ed_out_params = EdOutParams()
		self.add_param('ed_out_params:%i:SumPrint'%i, val=False)
		self.add_param('ed_out_params:%i:OutFile'%i, val=0)
		self.add_param('ed_out_params:%i:TabDelim'%i, val=False)
		self.add_param('ed_out_params:%i:OutFmt'%i, val='')
		self.add_param('ed_out_params:%i:TStart'%i, val=0.0)
		self.add_param('ed_out_params:%i:DecFact'%i, val=0.0)
		self.add_param('ed_out_params:%i:NTwGages'%i, val=0)
		self.add_param('ed_out_params:%i:TwrGagNd'%i, val=[])
		self.add_param('ed_out_params:%i:NBlGages'%i, val=0)
		self.add_param('ed_out_params:%i:BldGagNd'%i, val=[])

                ##################:%i:
		# Wind vartrees
                ###################
		#self.inflow_wind = InflowWind()
		self.add_param('inflow_wind:%i:Echo'%i, val=False)
		self.add_param('inflow_wind:%i:WindType'%i, val=0)
		self.add_param('inflow_wind:%i:PropagationDir'%i, val=0.)
		self.add_param('inflow_wind:%i:NWindVel'%i, val=0)
		self.add_param('inflow_wind:%i:WindVxiList'%i, val=0.)
		self.add_param('inflow_wind:%i:WindVyiList'%i, val=0.)
		self.add_param('inflow_wind:%i:WindVziList'%i, val=0.)

		#self.steady_wind_params = SteadyWindParams()
		self.add_param('steady_wind_params:%i:HWindSpeed'%i, val=0.)
		self.add_param('steady_wind_params:%i:RefHt'%i, val=0.)
		self.add_param('steady_wind_params:%i:PLexp'%i, val=0.)

		#self.uniform_wind_params = UniformWindParams()
		self.add_param('uniform_wind_params:%i:Filename'%i, val='')
		self.add_param('uniform_wind_params:%i:RefHt'%i, val=0.)
		self.add_param('uniform_wind_params:%i:RefLength'%i, val=0.)

		#self.turbsim_wind_params = TurbSimWindParams()
		self.add_param('turbsim_wind_params:%i:Filename'%i, val='')

		#self.bladed_wind_params = BladedWindParams()
		self.add_param('bladed_wind_params:%i:FilenameRoot'%i, val='')
		self.add_param('bladed_wind_params:%i:TowerFile'%i, val=False)

		#self.hawc_wind_params = HAWCWindParams()
		self.add_param('hawc_wind_params:%i:FileName_u'%i, val='')
		self.add_param('hawc_wind_params:%i:FileName_v'%i, val='')
		self.add_param('hawc_wind_params:%i:FileName_w'%i, val='')
		self.add_param('hawc_wind_params:%i:nx'%i, val=0)
		self.add_param('hawc_wind_params:%i:ny'%i, val=0)
		self.add_param('hawc_wind_params:%i:nz'%i, val=0)
		self.add_param('hawc_wind_params:%i:dx'%i, val=0.)
		self.add_param('hawc_wind_params:%i:dy'%i, val=0.)
		self.add_param('hawc_wind_params:%i:dz'%i, val=0.)
		self.add_param('hawc_wind_params:%i:RefHt'%i, val=0.)
		self.add_param('hawc_wind_params:%i:ScaleMethod'%i, val=0)
		self.add_param('hawc_wind_params:%i:SFx'%i, val=0.)
		self.add_param('hawc_wind_params:%i:SFy'%i, val=0.)
		self.add_param('hawc_wind_params:%i:SFz'%i, val=0.)
		self.add_param('hawc_wind_params:%i:SigmaFx'%i, val=0.)
		self.add_param('hawc_wind_params:%i:SigmaFy'%i, val=0.)
		self.add_param('hawc_wind_params:%i:SigmaFz'%i, val=0.)
		self.add_param('hawc_wind_params:%i:URef'%i, val=0.)
		self.add_param('hawc_wind_params:%i:WindProfile'%i, val=0)
		self.add_param('hawc_wind_params:%i:PLExp'%i, val=0.)
		self.add_param('hawc_wind_params:%i:Z0'%i, val=0.)


		#self.inflow_out_params = Inflow:%i:utParams()
		self.add_param('inflow_out_params:%i:SumPrint'%i, val=False)

		#self.wnd_wind = WndWind()
		self.add_param('wnd_wind:%i:TimeSteps'%i, val=0)
		self.add_param('wnd_wind:%i:Time'%i, val=zeros([1]))
		self.add_param('wnd_wind:%i:HorSpd'%i, val=zeros([1]))
		self.add_param('wnd_wind:%i:WindDir'%i, val=zeros([1]))
		self.add_param('wnd_wind:%i:VerSpd'%i, val=zeros([1]))
		self.add_param('wnd_wind:%i:HorShr'%i, val=zeros([1]))
		self.add_param('wnd_wind:%i:VerShr'%i, val=zeros([1]))
		self.add_param('wnd_wind:%i:LnVShr'%i, val=zeros([1]))
		self.add_param('wnd_wind:%i:GstSpd'%i, val=zeros([1]))

                ###################
		# AeroDyn vartrees
                ###################
		#self.aerodyn = AeroDyn()
		self.add_param('aerodyn:%i:SysUnits'%i, val='SI')
		self.add_param('aerodyn:%i:StallMod'%i, val='BEDOES')
		self.add_param('aerodyn:%i:UseCM'%i, val='NO_CM')
		self.add_param('aerodyn:%i:InfModel'%i, val='EQUIL')
		self.add_param('aerodyn:%i:IndModel'%i, val='SWIRL')
		self.add_param('aerodyn:%i:AToler'%i, val=0.)
		self.add_param('aerodyn:%i:TLModel'%i, val='PRANDtl')
		self.add_param('aerodyn:%i:HLModel'%i, val='PRANDTl')
		self.add_param('aerodyn:%i:WindFile'%i, val='')
		self.add_param('aerodyn:%i:wind_file_type'%i, val='hh')
		self.add_param('aerodyn:%i:HH'%i, val=0.)
		self.add_param('aerodyn:%i:TwrShad'%i, val=0.)
		self.add_param('aerodyn:%i:ShadHWid'%i, val=9999.9)
		self.add_param('aerodyn:%i:T_Shad_Refpt'%i, val=9999.9)
		self.add_param('aerodyn:%i:AirDens'%i, val=1.225)
		self.add_param('aerodyn:%i:KinVisc'%i, val=1.464e-5)
		self.add_param('aerodyn:%i:DTAero'%i, val=0.02479)

		#self.blade_aero = AeroDynBlade()
		self.add_param('blade_aero:%i:NumFoil'%i, val=0)
		self.add_param('blade_aero:%i:FoilNm'%i, val=zeros([1]))
		self.add_param('blade_aero:%i:af_data'%i, val=[])
		self.add_param('blade_aero:%i:BldNodes'%i, val=zeros([1]))
		self.add_param('blade_aero:%i:AeroTwst'%i, val=zeros([1]))
		self.add_param('blade_aero:%i:DRNodes'%i, val=zeros([1]))
		self.add_param('blade_aero:%i:Chord'%i, val=zeros([1]))
		self.add_param('blade_aero:%i:NFoil'%i, val=zeros([1]))
		self.add_param('blade_aero:%i:PrnElm'%i, val=zeros([1]))

                ###################
		# ServoDyn vartrees
                ###################
		#self.sd_sim_ctrl = SdSimCtrl()
		self.add_param('sd_sim_ctrl:%i:Echo'%i, val=False)
		self.add_param('sd_sim_ctrl:%i:DT'%i, val=0.)
                
		#self.pitch_ctrl = PitchCtrl()
		self.add_param('pitch_ctrl:%i:PCMode'%i, val=0)
		self.add_param('pitch_ctrl:%i:TPCOn'%i, val=0.)
		self.add_param('pitch_ctrl:%i:TPitManS1'%i, val=0.)
		self.add_param('pitch_ctrl:%i:TPitManS2'%i, val=0.)
		self.add_param('pitch_ctrl:%i:TPitManS3'%i, val=0.)
		self.add_param('pitch_ctrl:%i:TPitManE1'%i, val=0.)
		self.add_param('pitch_ctrl:%i:TPitManE2'%i, val=0.)
		self.add_param('pitch_ctrl:%i:TPitManE3'%i, val=0.)
		self.add_param('pitch_ctrl:%i:PitManRat1'%i, val=0.)
		self.add_param('pitch_ctrl:%i:PitManRat2'%i, val=0.)
		self.add_param('pitch_ctrl:%i:PitManRat3'%i, val=0.)
		self.add_param('pitch_ctrl:%i:BlPitchF1'%i, val=0.)
		self.add_param('pitch_ctrl:%i:BlPitchF2'%i, val=0.)
		self.add_param('pitch_ctrl:%i:BlPitchF3'%i, val=0.)
		self.add_param('pitch_ctrl:%i:BlPitch1'%i, val=0.)
		self.add_param('pitch_ctrl:%i:BlPitch2'%i, val=0.)

		#self.gen_torq_ctrl = GenTorqCtrl()
		self.add_param('gen_torq_ctrl:%i:VSContrl'%i, val=0)
		self.add_param('gen_torq_ctrl:%i:GenModel'%i, val=0)
		self.add_param('gen_torq_ctrl:%i:GenEff'%i, val=0.)
		self.add_param('gen_torq_ctrl:%i:GenTiStr'%i, val=False)
		self.add_param('gen_torq_ctrl:%i:GenTiStp'%i, val=False)
		self.add_param('gen_torq_ctrl:%i:SpdGenOn'%i, val=0.)
		self.add_param('gen_torq_ctrl:%i:TimGenOn'%i, val=0.)
		self.add_param('gen_torq_ctrl:%i:TimGenOf'%i, val=0.)

		#self.var_speed_torq_ctrl = VarSpeedTorqCtrl()
                self.add_param('var_speed_torq_ctrl:%i:VS_RtGnSp'%i, val=0.)
                self.add_param('var_speed_torq_ctrl:%i:VS_RtTq'%i, val=0.)
                self.add_param('var_speed_torq_ctrl:%i:VS_Rgn2K'%i, val=0.)
                self.add_param('var_speed_torq_ctrl:%i:VS_SlPc'%i, val=0.)

		#self.induct_gen = InductGen()
		self.add_param('induct_gen:%i:SIG_SlPc'%i, val=0.)
		self.add_param('induct_gen:%i:SIG_SySp'%i, val=0.)
		self.add_param('induct_gen:%i:SIG_RtTq'%i, val=0.)
		self.add_param('induct_gen:%i:SIG_PORt'%i, val=0.)

		#self.theveq_induct_gen = ThevEqInductGen()
		self.add_param('theveq_induct_gen:%i:TEC_Freq'%i, val=0.)
		self.add_param('theveq_induct_gen:%i:TEC_NPol'%i, val=0)
		self.add_param('theveq_induct_gen:%i:TEC_SRes'%i, val=0.)
		self.add_param('theveq_induct_gen:%i:TEC_RRes'%i, val=0.)
		self.add_param('theveq_induct_gen:%i:TEC_VLL'%i, val=0.)
		self.add_param('theveq_induct_gen:%i:TEC_SLR'%i, val=0.)
		self.add_param('theveq_induct_gen:%i:TEC_RLR'%i, val=0.)
		self.add_param('theveq_induct_gen:%i:TEC_MR'%i, val=0.)

		#self.shaft_brake = ShaftBrake()
		self.add_param('shaft_brake:%i:HSSBrMode'%i, val=0)
		self.add_param('shaft_brake:%i:THSSBrDp'%i, val=0.)
		self.add_param('shaft_brake:%i:HSSBrDT'%i, val=0.)
		self.add_param('shaft_brake:%i:HSSBrTqF'%i, val=0.)

		#self.nac_yaw_ctrl = NacYawCtrl()
		self.add_param('nac_yaw_ctrl:%i:YCMode'%i, val=0)
		self.add_param('nac_yaw_ctrl:%i:TYCOn'%i, val=0.)
		self.add_param('nac_yaw_ctrl:%i:YawNeut'%i, val=0.)
		self.add_param('nac_yaw_ctrl:%i:YawSpr'%i, val=0.)
		self.add_param('nac_yaw_ctrl:%i:YawDamp'%i, val=0.)
		self.add_param('nac_yaw_ctrl:%i:TYawManS'%i, val=0.)
		self.add_param('nac_yaw_ctrl:%i:YawManRat'%i, val=0.)
		self.add_param('nac_yaw_ctrl:%i:NacYawF'%i, val=0.)

		#self.tip_brake = TipBrake()
		self.add_param('tip_brake:%i:TiDynBrk'%i, val=0.)
		self.add_param('tip_brake:%i:TTpBrDp1'%i, val=0.)
		self.add_param('tip_brake:%i:TTpBrDp2'%i, val=0.)
		self.add_param('tip_brake:%i:TTpBrDp3'%i, val=0.)
		self.add_param('tip_brake:%i:TBDepISp1'%i, val=0.)
		self.add_param('tip_brake:%i:TBDepISp2'%i, val=0.)
		self.add_param('tip_brake:%i:TBDepISp3'%i, val=0.)
		self.add_param('tip_brake:%i:TBDrConN'%i, val=0.)
		self.add_param('tip_brake:%i:TBDrConD'%i, val=0.)
		self.add_param('tip_brake:%i:TpBrDT'%i, val=0.)

		#self.tuned_mass_damper = TunedMassDamp()
		self.add_param('tuned_mass_damper:%i:CompNTMD'%i, val=0.)
		self.add_param('tuned_mass_damper:%i:NTMDfile'%i, val='')
		self.add_param('tuned_mass_damper:%i:CompTTMD'%i, val=0.)
		self.add_param('tuned_mass_damper:%i:TTMDfile'%i, val='')

		#self.bladed_interface = BladedInterface()
		self.add_param('bladed_interface:%i:DLL_FileName'%i, val='')
		self.add_param('bladed_interface:%i:DLL_InFile'%i, val='')
		self.add_param('bladed_interface:%i:DLL_ProcName'%i, val='')
		self.add_param('bladed_interface:%i:DLL_DT'%i, val='')
		self.add_param('bladed_interface:%i:DLL_Ramp'%i, val=False)
		self.add_param('bladed_interface:%i:BPCutoff'%i, val=0.)
		self.add_param('bladed_interface:%i:NacYaw_North'%i, val=0.)
		self.add_param('bladed_interface:%i:Ptch_Cntrl'%i, val=0.)
		self.add_param('bladed_interface:%i:Ptch_SetPnt'%i, val=0.)
		self.add_param('bladed_interface:%i:Ptch_Min'%i, val=0.)
		self.add_param('bladed_interface:%i:Ptch_Max'%i, val=0.)
		self.add_param('bladed_interface:%i:PtchRate_Min'%i, val=0.)
		self.add_param('bladed_interface:%i:PtchRate_Max'%i, val=0.)
		self.add_param('bladed_interface:%i:Gain_OM'%i, val=0.)
		self.add_param('bladed_interface:%i:GenSpd_MinOM'%i, val=0.)
		self.add_param('bladed_interface:%i:GenSpd_MaxOM'%i, val=0.)
		self.add_param('bladed_interface:%i:GenSpd_Dem'%i, val=0.)
		self.add_param('bladed_interface:%i:GenPwr_Dem'%i, val=0.)
		self.add_param('bladed_interface:%i:DLL_NumTrq'%i, val=0.)
		self.add_param('bladed_interface:%i:GenSpd_TLU'%i, val=zeros([0]))
		self.add_param('bladed_interface:%i:GenTrq_TLU'%i, val=zeros([0]))

		#self.sd_out_params = SdOutParams()
		self.add_param('sd_out_params:%i:SumPrint'%i, val=False)
		self.add_param('sd_out_params:%i:OutFile'%i, val=0)
		self.add_param('sd_out_params:%i:TabDelim'%i, val=False)
		self.add_param('sd_out_params:%i:OutFmt'%i, val='')
		self.add_param('sd_out_params:%i:TStart'%i, val=0.)
		
		# List of Outputs (all input files -- FST, ED, SD)
		# TODO:%i: Update FstOutput for a few new outputs in FAST8
		#self.outlist = FstOutput()   # 
		self.add_param('outlist:%i:description'%i, val='')











